#!/bin/sh
# Prevent you from pushing commits that have "WIP" in the message

branch=`git branch 2>/dev/null | grep '^*' | colrm 1 2`

git log $branch ^origin/$branch --pretty="format:%h %s" | grep "WIP"

if [[ $? -eq 0 ]]; then
  echo "Found commits with WIP messages"
  exit 1
fi

exit 0
