#!/bin/bash

SCRIPT_FILE_NAME=$(basename $0)
SCRIPT_NAME=${SCRIPT_FILE_NAME%.*}
SELF=$(cd $(dirname $0); pwd)
VERSION="1.2.1"
LOGGING=false
SEPARATER='---------------------------'

function _usage() {
    echo "Usage: ${SCRIPT_NAME} [OPTIONS] [SEED_FILE]"
    echo "  This script is ~."
    echo
    echo "Options:"
    echo "  -h, --help                     Show help."
    echo "  -v, --version                  Show script version."
    echo "  -e, --extension val            Limit the output file to the extension of siblings."
    echo "  -d, --delimiter val            Delimiter at output."
    echo "      --dotfile                  Also outputs a dot file."
    echo "  -o, --output val               List file in the specified file."
    echo "  -a                             Output with absolute path."
    echo "  -c                             Show the number of files."
    echo "      --verbose                  Print various logging information"
    echo
    exit 0
}

function _log() {
    ${LOGGING} && echo "$@" || return 0
}

function _err() {
    echo "${SCRIPT_NAME}: $1" && exit ${2:-1}
}

function _args_count() {
    echo ${#ARG_VALUES[@]}
}

function _is_exist() {
    [ -f $1 ] || [ -d $1 ] || [[ $(type $1) ]]
}

function _verbose() {
    _log "DIR: ${DIR}"
    _log "EXT: ${EXT[@]}"
    _log "IS_ABSOLUTE_PATH: ${IS_ABSOLUTE_PATH}"
    _log "IS_SHOW_DOT_FILE: ${IS_SHOW_DOT_FILE}"
    _log "DELIMITER: ${DELIMITER}"
    _log "OUTPUT_FILE: ${OUTPUT_FILE}"
    _log "IS_COUNT: ${IS_COUNT}"
    _log "${SEPARATER}"
}

DIR=''
EXT=()
IS_ABSOLUTE_PATH=false
IS_SHOW_DOT_FILE=false
DELIMITER='\n'
IS_COUNT=false
OUTPUT_FILE=""

function _main() {
    local results=()
    while read -r file; do

        local is_print_ok=true
        local is_dot_file=false

        file=$(echo "${file}" | sed 's:^\./::')

        local filename=$(basename ${file})
        if [ ${filename:0:1} == '.' ]; then
            ${IS_SHOW_DOT_FILE} || continue
        fi

        [ ! -z ${EXT} ] && {
            if [[ " ${EXT[@]} " =~ " ${file##*.} " ]]; then
                is_print_ok=true
            else
                is_print_ok=false
            fi
        }

        ${is_print_ok} && {
            ${IS_ABSOLUTE_PATH} && {
                results+=("${SELF}/${file}")
            } || {
                results+=("${file}")
            }
        }
    done < <(find ${DIR} -type f -mindepth 1 -maxdepth 1)

    ${IS_COUNT} && echo ${#results[@]} && exit 0

    [ "${DELIMITER}" = '\n' ] && {
      ( IFS=$'\n'
         [ ! -z ${OUTPUT_FILE} ] \
             && echo "${results[*]}" > ${OUTPUT_FILE} \
             || echo "${results[*]}"
      )
    } || {
      ( IFS=$'\n'
        for i in ${results[@]}; do
            local str+="${i}${DELIMITER}"
        done
        str=$(echo ${str} | sed "s/${DELIMITER}$//")
        [ ! -z ${OUTPUT_FILE} ] \
            && echo ${str} > ${OUTPUT_FILE} \
            || echo ${str}
      )
    }
}

# -------------------------------------------------------------
# Arguments and Options
# -------------------------------------------------------------

ARG_VALUES=()

function _analyse_args_and_options() {
    while (( $# > 0 ))
    do
        case $1 in
            -h | --help)
                _usage
                exit 1
                ;;
            -v | --version)
                echo ${SCRIPT_NAME} v${VERSION}
                exit 0
                ;;
            --verbose)
                LOGGING=true
                shift
                ;;

            # Must have argument
            -e | --extention)
                if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
                    _err "-e option requires a value."
                fi
                EXT+=($2)
                shift 2
                ;;

            # Must have argument
            -d | --delimiter)
                if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
                    _err "-d option requires a value."
                fi
                DELIMITER=$2
                shift 2
                ;;

            # Must have argument
            -o | --output)
                if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
                    _err "-o option requires a value."
                fi
                OUTPUT_FILE=$2
                shift 2
                ;;

            # after this all args include '-xx', will treat arg value
            -- | -)
                shift
                ARG_VALUES+=( "$@" )
                break
                ;;

            # for true or false flags, no argument
            --*)
                if [[ "$1" =~ 'dotfile' ]]; then
                    IS_SHOW_DOT_FILE=true
                fi
                shift
                ;;

            # for true or false flags, no argument
            -*)
                if [[ "$1" =~ 'a' ]]; then
                    IS_ABSOLUTE_PATH=true
                fi
                if [[ "$1" =~ 'c' ]]; then
                    IS_COUNT=true
                fi
                shift
                ;;

            # for arguments
            *)
                ARG_VALUES+=("$1")
                shift
                ;;
        esac
    done
}

function _set_variables() {
    DIR=${ARG_VALUES[0]:=.}
    return 0
}

function _verify_variables() {
    local ng=('^' '*' '-' '\' '/' '[' ']')
    if [[ "${ng[@]}" =~ "${DELIMITER}" ]]; then
        _err "bad delimiter"
    fi

    [ ! -d ${DIR} ] && _err "No such directory"

    if [[ -e ${OUTPUT_FILE} ]]; then
        _err "The specified file already exists"
    fi
    return 0
}

# -------------------------------------------------------------
# Main Routine
# -------------------------------------------------------------
_analyse_args_and_options $@ && {
    _set_variables && _verify_variables && {
        _verbose
        _log 'start main process..' && _log "${SEPARATER}"
        _main
    }
}

exit 0
