#!/bin/bash

SCRIPT_FILE_NAME=$(basename $0)
SCRIPT_NAME=${SCRIPT_FILE_NAME%.*}
SELF=$(cd $(dirname $0); pwd)
VERSION="1.0.0"
LOGGING=false
SEPARATER='---------------------------'

function _usage() {
    echo "Usage: ${SCRIPT_NAME} [OPTIONS] [SEED_FILE]"
    echo "  This script is ~."
    echo
    echo "Options:"
    echo "  -h, --help                     Show help."
    echo "  -v, --version                  Show script version."
    echo "  -e, --extension ARG            list file specified file extention."
#    echo "  -b, --long-b [ARG]             sample option: either with or without argument."
#    echo "  -c, --long-c                   sample option: have no argument."
#    echo "  -, --                          after this, all value will be argument(s)."
    echo "      --dotfile                  list dotfile(s)."
    echo "  -a                             list file in absolute file path."
#    echo "  -p                             sample flag option."
    echo "      --verbose                  Print various logging information"
    echo
    exit 1
}

function _log() {
    ${LOGGING} && echo "$@" || return 0
}

function _err() {
    echo "[err] $1" && exit 1
}

function _args_count() {
    echo ${#ARG_VALUES[@]}
}

function _is_exist() {
    [ -f $1 ] || [ -d $1 ] || [[ $(type $1) ]]
}

function _verbose() {
    _log "DIR: ${DIR}"
    _log "EXT: ${EXT[@]}"
    _log "IS_ABSOLUTE_PATH: ${IS_ABSOLUTE_PATH}"
    _log "IS_SHOW_DOT_FILE: ${IS_SHOW_DOT_FILE}"
    _log "${SEPARATER}"
}

DIR=''
EXT=()
IS_ABSOLUTE_PATH=false
IS_SHOW_DOT_FILE=false

function _main() {
    while read -r file; do

        local is_print_ok=true
        local is_dot_file=false

        file=$(echo ${file} | sed 's:^\./::')
        if [ ${file:0:1} == '.' ]; then
            ${IS_SHOW_DOT_FILE} || {
                continue
            }
        fi

        [ ! -z ${EXT} ] && {
            is_print_ok=false
            for e in ${EXT[@]}; do
                if [ "${e}" = "${file##*.}" ]; then
                   is_print_ok=true
                   break
                fi
            done
        }

        ${is_print_ok} &&  {
            ${IS_ABSOLUTE_PATH} && {
                echo "${SELF}/${file}"
            } || {
                echo "${file}"
            }
        }
    done < <(find ${DIR} -type f -mindepth 1 -maxdepth 1)
}

# -------------------------------------------------------------
# Arguments and Options
# -------------------------------------------------------------

ARG_VALUES=()
SAMPLE_OPTION_A=""
SAMPLE_OPTION_B=""
SAMPLE_OPTION_FLAG_N=false
SAMPLE_OPTION_FLAG_L=false
SAMPLE_OPTION_FLAG_P=false

function _analyse_args_and_options() {
    while (( $# > 0 ))
    do
        case $1 in
            -h | --help)
                _usage
                exit 1
                ;;
            -v | --version)
                echo ${SCRIPT_NAME} v${VERSION}
                exit 0
                ;;
            --verbose)
                LOGGING=true
                shift
                ;;
            -e | --extention)                  # Must have argument
                if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
                    _err "-e option requires a value."
                fi
                EXT+=($2)
                shift 2
                ;;
#            -b | --long-b)                  # Either with or without argument is possible
#                set +u
#                if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
#                    shift
#                else
#                    SAMPLE_OPTION_B=$2
#                    shift 2
#                fi
#                set -u
#                ;;
#            -c | --long-c)                  # no argument
#                shift
#                ;;
            -- | -) # after this all args include '-xx', will treat arg value
                shift
                ARG_VALUES+=( "$@" )
                break
                ;;
            --*) # for true or false flags, no argument
                if [[ "$1" =~ 'dotfile' ]]; then
                    IS_SHOW_DOT_FILE=true
                fi
                shift
                ;;
            -*) # for true or false flags, no argument
                if [[ "$1" =~ 'a' ]]; then
                    IS_ABSOLUTE_PATH=true
                fi
                shift
                ;;
            *)
                ARG_VALUES+=("$1")
                shift
                ;;
        esac
    done
}

function _set_variables() {
    DIR=${ARG_VALUES[0]}
}

function _verify_variables() {
    [ -z ${DIR} ] && _err "You need to specify directory."
    [ ! -d ${DIR} ] && _err "No such directory."
    :
}

# -------------------------------------------------------------
# Main Routine
# -------------------------------------------------------------
_analyse_args_and_options $@ && {
    _set_variables && _verify_variables && {
        _verbose
        _log 'start main process..' && _log "${SEPARATER}"
        _main
    }
}
exit 0
